In [10]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [11]:
num=50
roll_no=[i for i in range(1,num+1)]
name=[f"student_{i}" for i in range(1,num+1)]
height=np.random.randint(150,190,size=50)
weight=np.random.randint(50,90,size=50)

In [12]:
data={
    "roll":roll_no,
    "name":name,
    "height":height,
    "weight":weight
}

In [13]:
df=pd.DataFrame(data,index=[i for i in range(1,num+1)])

In [14]:
print(df)

    roll        name  height  weight
1      1   student_1     158      60
2      2   student_2     163      88
3      3   student_3     158      70
4      4   student_4     187      55
5      5   student_5     163      67
6      6   student_6     173      75
7      7   student_7     166      73
8      8   student_8     173      68
9      9   student_9     153      77
10    10  student_10     187      59
11    11  student_11     150      54
12    12  student_12     150      85
13    13  student_13     177      58
14    14  student_14     151      70
15    15  student_15     156      66
16    16  student_16     174      51
17    17  student_17     154      64
18    18  student_18     176      59
19    19  student_19     169      63
20    20  student_20     189      82
21    21  student_21     176      58
22    22  student_22     155      55
23    23  student_23     168      62
24    24  student_24     165      59
25    25  student_25     185      85
26    26  student_26     173      88
27    27  student_27     189      55
28    28  student_28     151      66
29    29  student_29     164      77
30    30  student_30     182      64
31    31  student_31     189      84
32    32  student_32     155      82
33    33  student_33     168      81
34    34  student_34     162      77
35    35  student_35     155      51
36    36  student_36     169      69
37    37  student_37     162      80
38    38  student_38     187      63
39    39  student_39     157      84
40    40  student_40     160      69
41    41  student_41     170      89
42    42  student_42     162      61
43    43  student_43     180      69
44    44  student_44     187      72
45    45  student_45     169      85
46    46  student_46     182      67
47    47  student_47     185      51
48    48  student_48     173      89
49    49  student_49     162      60
50    50  student_50     161      60

In [15]:
df_normalized=df.copy()
cols_to_normalise=["height","weight"]
for col in cols_to_normalise:
    col_min=df[col].min()
    col_max=df[col].max()
    df_normalized[col] = (df[col] - col_min) / (col_max-col_min)
print(df_normalized.head(2))

   roll       name    height    weight
1     1  student_1  0.205128  0.236842
2     2  student_2  0.333333  0.973684

In [16]:
mm=MinMaxScaler()
df2=pd.DataFrame(mm.fit_transform(df[["height","weight"]]))
df2

           0         1
0   0.205128  0.236842
1   0.333333  0.973684
2   0.205128  0.500000
3   0.948718  0.105263
4   0.333333  0.421053
5   0.589744  0.631579
6   0.410256  0.578947
7   0.589744  0.447368
8   0.076923  0.684211
9   0.948718  0.210526
10  0.000000  0.078947
11  0.000000  0.894737
12  0.692308  0.184211
13  0.025641  0.500000
14  0.153846  0.394737
15  0.615385  0.000000
16  0.102564  0.342105
17  0.666667  0.210526
18  0.487179  0.315789
19  1.000000  0.815789
20  0.666667  0.184211
21  0.128205  0.105263
22  0.461538  0.289474
23  0.384615  0.210526
24  0.897436  0.894737
25  0.589744  0.973684
26  1.000000  0.105263
27  0.025641  0.394737
28  0.358974  0.684211
29  0.820513  0.342105
30  1.000000  0.868421
31  0.128205  0.815789
32  0.461538  0.789474
33  0.307692  0.684211
34  0.128205  0.000000
35  0.487179  0.473684
36  0.307692  0.763158
37  0.948718  0.315789
38  0.179487  0.868421
39  0.256410  0.473684
40  0.512821  1.000000
41  0.307692  0.263158
42  0.769231  0.473684
43  0.948718  0.552632
44  0.487179  0.894737
45  0.820513  0.421053
46  0.897436  0.000000
47  0.589744  1.000000
48  0.307692  0.236842
49  0.282051  0.236842

In [17]:
ss=StandardScaler()
df3=pd.DataFrame(ss.fit_transform(df[["height","weight"]]))
df3

           0         1
0  -0.885179 -0.804264
1  -0.467642  1.664968
2  -0.885179  0.077604
3   1.536538 -1.245198
4  -0.467642 -0.186956
5   0.367433  0.518539
6  -0.217119  0.342165
7   0.367433 -0.098769
8  -1.302717  0.694912
9   1.536538 -0.892451
10 -1.553239 -1.333385
11 -1.553239  1.400407
12  0.701463 -0.980638
13 -1.469732  0.077604
14 -1.052194 -0.275143
15  0.450940 -1.597946
16 -1.219209 -0.451517
17  0.617955 -0.892451
18  0.033403 -0.539704
19  1.703553  1.135847
20  0.617955 -0.980638
21 -1.135702 -1.245198
22 -0.050104 -0.627890
23 -0.300627 -0.892451
24  1.369523  1.400407
25  0.367433  1.664968
26  1.703553 -1.245198
27 -1.469732 -0.275143
28 -0.384134  0.694912
29  1.119000 -0.451517
30  1.703553  1.312220
31 -1.135702  1.135847
32 -0.050104  1.047660
33 -0.551149  0.694912
34 -1.135702 -1.597946
35  0.033403 -0.010582
36 -0.551149  0.959473
37  1.536538 -0.539704
38 -0.968687  1.312220
39 -0.718164 -0.010582
40  0.116910  1.753155
41 -0.551149 -0.716077
42  0.951985 -0.010582
43  1.536538  0.253978
44  0.033403  1.400407
45  1.119000 -0.186956
46  1.369523 -1.597946
47  0.367433  1.753155
48 -0.551149 -0.804264
49 -0.634657 -0.804264

In [18]:
df_standarized=df.copy()
cols_to_standardise=["height","weight"]
for col in cols_to_standardise:
    col_mean=df[col].mean()
    col_std=df[col].std()
    df_standarized[col] = (df[col] - col_mean) / (col_std)
print(df_standarized.head(2))

   roll       name    height    weight
1     1  student_1 -0.876283 -0.796181
2     2  student_2 -0.462942  1.648234